# Global redirection: http to https
[http.routers.http-www-catchall]
  rule = "HostRegexp(`{host:(www\\.)?.+}`)"
  entryPoints = ["http"]
  middlewares = ["wwwtohttps"]
  service = "noop-www"

# Global redirection: https (www.) to https
[http.routers.https-www-catchall]
  rule = "HostRegexp(`{host:(www\\.).+}`)"
  entryPoints = ["https"]
  middlewares = ["wwwtohttps"]
  service = "noop-www"
  [http.routers.https-www-catchall.tls]

# middleware: http(s)://(www.) to  https://
[http.middlewares.wwwtohttps.redirectregex]
  regex = "^https?://(?:www\\.)?(.+)"
  replacement = "https://${1}"
  permanent = true

# NOOP service
[http.services.noop-www]
  [[http.services.noop-www.loadBalancer.servers]]
    url = "http://192.168.0.1:666"